version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - minio
      - redis
    networks:
      - app-network

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env.db
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d nestjs_architecture -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - .env.minio
    volumes:
      - 'minio_data:/data'
    command: server ../data --console-address ":9001"
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
