export const ENV_KEYS = {
  BASE_URL: 'BASE_URL',
  PORT: 'PORT',

  PASSWORD_HASH: 'PASSWORD_HASH',

  JWT_ACCESS_TOKEN_EXPIRATION: 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_REFRESH_TOKEN_EXPIRATION: 'JWT_REFRESH_TOKEN_EXPIRATION',
  JWT_SECRET: 'JWT_SECRET',

  SWAGGER_TITLE: 'SWAGGER_TITLE',
  SWAGGER_DESCRIPTION: 'SWAGGER_DESCRIPTION',
  SWAGGER_VERSION: 'SWAGGER_VERSION',
  SWAGGER_PATH: 'SWAGGER_PATH',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',

  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',
};
